version: 0.0
os: linux
files:
- source: /
destination: /tmp/
hooks:
AfterInstall:
- location: viewModel/install_dependencies
timeout: 100
runas: root
ApplicationStart:
- location: viewModel/start_server
timeout: 100
runas: root
ValidateService:
- location: scripts/test
timeout: 100
runas: root
