version: 0.0 
os: linux
files:
  - source: /
    destination: /var/www/
hooks:
  BeforeInstall:
    - location: viewModel/install_dependencies.sh
  ApplicationStart:
    - location: viewModel/start_server.sh
  ValidateService:
    - location: viewModel/validate_server.sh
